defaultEntryPoints = ["web", "websecure"]

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true

[certificatesResolvers.letsencrypt.acme]
  email = "{hush}"
  storage = "./acme.json"
  # Staging server 
  #caServer = "https://acme-staging-v02.api.letsencrypt.org/directory" 
  [certificatesResolvers.letsencrypt.acme.tlsChallenge]
  
[providers.docker]
  watch = true
  network = "web"  

[providers.file]
    filename = "traefik_dynamic.toml"
